config/routes.rb
Rails.application.routes.draw do
    
    resources :items  do
     resources :item_histories, only: [:index, :create] do
      end
    end
    devise_for :users,
      controllers: {
         omniauth_callbacks: 'users/omniauth_callbacks'
      }
    resources :employees do
      member do
       get :download_profile
      end
    end
  resources :documents
  get "about" => "pages#about_us"
  get "contact" => "pages#contact_us"
  get "privacy-policy" => "pages#privacy_policy"
  get "terms-and-conditions" => "pages#terms_and_conditions"

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  root "home#index"
end

app/models/item.rb
class Item < ApplicationRecord
   belongs_to :employee, optional: true
  has_many :item_histories, dependent: :destroy
  validates :name, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :show]
  before_action :authorize_admin_or_manager, only: [:new, :create, :edit, :update]
  before_action :authorize_employee_access, only: [:show]
  before_action :filter_documents, only: [:index]
  def index
    # @items = Item.all
    # Rails.logger.debug(@items.inspect)
  end

  def new
    @item = Item.new
  end

  def create
  @item = Item.new(item_params) # Initialize the item with the form parameters

    if @item.save
    # History or other logic goes here
    redirect_to items_path, notice: "Item successfully created."
    else
    # If the item is not saved, render the new form with error messages
    render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    @histories = @item.item_histories.order(created_at: :desc)
  end

  def update
   @item = Item.find(params[:id])
     if params[:item][:returned_date].present?
      @item.employee_id = nil
      @item.issued_date = nil
     end
      if params[:item][:employee_id].present?
      @item.returned_date = nil
      end
    if @item.update(item_params)
       redirect_to items_path, notice: "Item successfully updated."
    else
    render :edit
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  # Ensures only admins or HR can create new documents
  def authorize_admin_or_manager
    unless current_user&.role.in?(['admin', 'manager'])
      redirect_to items_path, alert: "You are not authorized to perform this action."
    end
  end

  # Restricts access to an employee's own documents or allows admin/HR access
  def authorize_employee_access
    return if current_user&.role.in?(['admin', 'manager'])

    if current_user&.role == 'employee' && @item.employee_id != current_user.id
      redirect_to items_path, alert: "You are not authorized to access this item."
    end
  end

  # Filters documents based on the role
  def filter_documents
    if current_user&.role.in?(['admin', 'manager'])
      @items = Item.all # Admins and HR see all documents
    elsif current_user&.role == 'employee'
      @items = Item.where(employee_id: current_user.id) # Employees see only their own documents
    else
      @items = Item.none # Unauthorized users see no documents
    end
  end

  # Strong parameters for document creation and updating
  def item_params
    params.require(:item).permit(:issued_to, :sr_no, :name, :price, :employee_id, :issued_date, :returned_date)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="col-lg-12">
  <!-- Card with Light Background and Primary Border -->
   <<div class="col-lg-12">
 <div class="d-flex justify-content-center align-items-center fw-bolder ">
 <div class="card  bg-info text-light border-dark  " style="box-shadow: 0 8px 16px rgba(255, 255, 255, 0.2), 0 4px 6px rgba(255, 255, 255, 0.1); width: 70%;">
    <div class="card-body text-center ">
      <h2 class="text-primary-emphasis">Assign Items</h2>
    </div>
  </div>
  </div>

  <!-- Notifications Section -->
  

  <!-- Form to Create New Item -->
  <%= form_with model: @item, local: true do |form| %>

  <div class="form-group">
  <%= form.label :employee_id, 'Assigned To', class: 'form-label text-dark' %>
       <%= form.select :employee_id, 
                  options_for_select(Employee.all.map { |e| [e.name, e.id] } + [['N/A', -1]], selected: @item.employee_id),
                  { prompt: 'Select an Employee' }, 
                  class: 'form-control bg-light text-dark', required: true %>
                  <div class="form-check ms-3">
     
</div>



   <div class="form-group">
  <%= form.label :issued_date, 'Assigned Date', class: 'mb-2 mt-2 text-dark' %>
<%= form.date_field :issued_date, { include_blank: true, class: 'form-control bg-light text-dark' } %>
   </div>


    <div class="form-group text-center">
      <%= form.submit 'Assign Item', class: 'btn btn-success btn-lg mb-4 mt-4 d-block mx-auto rounded-pill', 
                      style: "box-shadow: 0 8px 16px rgba(255, 255, 255, 0.2), 0 4px 6px rgba(255, 255, 255, 0.1);width: 30%" %>
    </div>
  <% end %>

  <!-- Back to Item List Link -->
  <%= link_to 'Back to Items List', items_path, 
              class: "btn btn-outline-primary btn-lg mb-4 d-block mx-auto rounded-pill", 
              style: "box-shadow: 0 8px 16px rgba(255, 255, 255, 0.2), 0 4px 6px rgba(255, 255, 255, 0.1); width: 30%;" %>
</div>

app/views/items/index.html.erb
<div class="col-lg-12">
    <div class="d-flex justify-content-center align-items-center fw-bolder ">
 <div class="card  bg-info text-light border-dark  " style="box-shadow: 0 8px 16px rgba(255, 255, 255, 0.2), 0 4px 6px rgba(255, 255, 255, 0.1); width: 35%;">
    <div class="card-body text-center ">
      <h2 class="text-primary-emphasis">All Items Details</h2>
    </div>
  </div>
 
  </div>


  <!-- Notifications Section -->
 

  <!-- Create New Item Link -->
  <%= link_to 'Create New Item', new_item_path, 
              class: "btn btn-success btn-lg mt-4 mb-4 d-block mx-auto rounded-pill", 
              style: "box-shadow: 0 8px 16px rgba(255, 255, 255, 0.2), 0 4px 6px rgba(255, 255, 255, 0.1); width: 30%;" %>

  <!-- Table of Items -->
  <% if  @items.present? %>
    <table class="table rounded-lg table-secondary table-bordered table-striped table-hover mb-5">
  <thead class="bg-primary text-dark fw-bold">
        <tr>
          <th>S.N.</th>
          <th>Name</th>
          <th>Price</th>
          <th>Assigned To</th>
          <th>Assigned Date</th>
          <th>Return Date</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each_with_index do |item, index| %>
          <tr class="document-hover">
            <td><%= index + 1 %></td>
            <td><%= item.name %></td>
            <td><%= number_to_currency(item.price, unit: "₹", delimiter: ",", format: "%u%n") %></td>

            <td><%= item.employee&.name || "N/A" %></td>
            <td><%= item.issued_date || "N/A" %></td>
            <td><%= item.returned_date || "N/A" %></td>
            <td>
              <div class="dropdown">
                <button class="btn btn-outline-primary text-bold dropdown-toggle" type="button" 
                        id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                  Action
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  
                  <% unless item.employee.present? %>
                  <li><%= link_to "Assign", edit_item_path(item, item.id),  class: "dropdown-item return-btn" %></li>
                  <% end %>

              
                  <li><%= link_to "Return",  item_path(item, item.id), class: "dropdown-item" %></li>
                 <li><%= link_to "History", item_item_histories_path(item), class: "dropdown-item" %></li>


                </ul>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="text-center text-warning">No items available for you at the moment.</p>
  <% end %>
</div>

<!-- Custom CSS for Hover Effect -->
<style>
  .document-hover:hover {
    background-color: #007bff !important; /* Primary color */
    color: white !important; /* Ensure text stays white */
  }

  .document-hover {
    transition: background-color 0.3s ease, color 0.3s ease;
  }
</style>

app/views/items/new.html.erb
<div class="col-lg-12">
  <!-- Card with Light Background and Primary Border -->
  <div class="col-lg-12">
 <div class="d-flex justify-content-center align-items-center fw-bolder ">
 <div class="card  bg-info text-light border-dark  " style="box-shadow: 0 8px 16px rgba(255, 255, 255, 0.2), 0 4px 6px rgba(255, 255, 255, 0.1); width: 70%;">
    <div class="card-body text-center ">
      <h2 class="text-primary-emphasis">Create New Items</h2>
    </div>
  </div>
  </div>

  <!-- Notifications Section -->


  <!-- Form to Create New Item -->
  <%= form_with model: @item, local: true do |form| %>
    <div class="form-group">
      <%= form.label :name, 'Item Name', class: 'form-label text-dark' %>
      <%= form.text_field :name, class: 'form-control bg-light text-dark', required: true %>
    </div>

    <div class="form-group">
      <%= form.label :price, 'Price', class: 'form-label text-dark' %>
      <%= form.number_field :price, class: 'form-control bg-light text-dark', step: '0.01', required: true %>
    </div>
 
    <div class="form-group text-center">
      <%= form.submit 'Create Item', class: 'btn btn-success btn-lg mb-4 mt-4 d-block mx-auto rounded-pill', 
                      style: "box-shadow: 0 8px 16px rgba(255, 255, 255, 0.2), 0 4px 6px rgba(255, 255, 255, 0.1);width: 20%;" %>
    </div>
  <% end %>

  <!-- Back to Item List Link -->
  <%= link_to 'Back to Items List', items_path, 
              class: "btn btn-outline-primary btn-lg mb-4 d-block mx-auto rounded-pill", 
              style: "box-shadow: 0 8px 16px rgba(255, 255, 255, 0.2), 0 4px 6px rgba(255, 255, 255, 0.1); width: 30%;" %>
</div>

app/views/items/show.html.erb
<div class="col-lg-12">
  <!-- Card with Light Background and Primary Border -->
  <div class="col-lg-12">
    <div class="d-flex justify-content-center     align-items-center fw-bolder ">
       <div class="card  bg-info text-light border-dark  " style="box-shadow: 0 8px 16px rgba(255, 255, 255, 0.2), 0 4px 6px rgba(255, 255, 255, 0.1); width: 70%;">
      <div class="card-body text-center ">
      <h2 class="text-primary-emphasis">Return Items</h2>
    </div>
  </div>
  </div>

  <!-- Notifications Section -->
  
  <!-- Form to Create New Item -->
  <%= form_with model: @item, local: true do |form| %>

  



   <div class="form-group">
     <%= form.label :returned_date, 'Returned Date', class: 'mb-2 mt-2 text-dark' %>
     <%= form.date_field :returned_date, { include_blank: true, class: 'form-control bg-light text-dark' } %>
   </div>


    <div class="form-group text-center">
      <%= form.submit 'Returned Date', class: 'btn btn-success btn-lg mb-4 mt-4 d-block mx-auto rounded-pill',style: "box-shadow: 0 8px 16px rgba(255, 255, 255, 0.2), 0 4px 6px rgba(255, 255, 255, 0.1);width: 35%" %>
    </div>
  <% end %>

  <!-- Back to Item List Link -->
  <%= link_to 'Back to Items List', items_path, 
              class: "btn btn-outline-primary btn-lg mb-4 mt-4 d-block mx-auto rounded-pill", 
              style: "box-shadow: 0 8px 16px rgba(255, 255, 255, 0.2), 0 4px 6px rgba(255, 255, 255, 0.1); width: 35%;" %>
</div>